import { Produto } from '@/types/produto';

export const PRODUTOS: Produto[] = [
  {
    id: 1,
    title: 'Essence Mascara Lash Princess',
    description: 'Rímel de grande volume.',
    price: 9.99,
    discountPercentage: 7.17,
    rating: 4.94,
    stock: 5,
    brand: 'Essence',
    category: 'beauty',
    thumbnail: 'https://cdn.dummyjson.com/products/images/beauty/Essence%20Mascara%20Lash%20Princess/thumbnail.png',
    images: [],
  },
  {
    id: 2,
    title: 'Eyeshadow Palette with Mirror',
    description: 'Paleta de sombras com diversas cores.',
    price: 19.99,
    discountPercentage: 15.5,
    rating: 3.8,
    stock: 12,
    brand: 'Glamour Beauty',
    category: 'beauty',
    thumbnail: 'https://cdn.dummyjson.com/products/images/beauty/Eyeshadow%20Palette%20with%20Mirror/thumbnail.png',
    images: [],
  },
  {
    id: 3,
    title: 'Powder Canister Matte Finish',
    description: 'Pó facial de acabamento fosco duradouro.',
    price: 14.99,
    discountPercentage: 10.0,
    rating: 4.2,
    stock: 8,
    brand: 'Velvet Touch',
    category: 'beauty',
    thumbnail: 'https://cdn.dummyjson.com/products/images/beauty/Powder%20Canister/thumbnail.png',
    images: [],
  },
  {
    id: 4,
    title: 'Chanel Coco Noir Eau De',
    description: 'Coco Noir Eau de Parfum Spray.',
    price: 49.99,
    discountPercentage: 18.0,
    rating: 4.6,
    stock: 3,
    brand: 'Chanel',
    category: 'fragrances',
    thumbnail: 'https://cdn.dummyjson.com/products/images/fragrances/Chanel%20Coco%20Noir%20Eau%20De/thumbnail.png',
    images: [],
  },
];
